/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#916f6b",
        "on-tertiary-fixed-variant": "#404754",
        "surface-tint": "#c00018",
        "on-secondary-fixed": "#141b2b",
        "secondary-container": "#d9dff5",
        "tertiary-fixed-dim": "#c0c7d6",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "inverse-primary": "#ffb3ac",
        "on-primary-container": "#fffbff",
        "surface-variant": "#e1e3e4",
        "secondary-fixed": "#dce2f7",
        "on-tertiary": "#ffffff",
        "secondary": "#575e70",
        "surface-container-lowest": "#ffffff",
        "background": "#f8f9fa",
        "outline-variant": "#e6bdb9",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdad6",
        "on-surface": "#191c1d",
        "surface-bright": "#f8f9fa",
        "on-error": "#ffffff",
        "tertiary": "#555c6a",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#410003",
        "on-primary-fixed-variant": "#930010",
        "on-secondary-fixed-variant": "#404758",
        "on-secondary-container": "#5c6274",
        "error": "#ba1a1a",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "on-surface-variant": "#5d3f3c",
        "inverse-on-surface": "#f0f1f2",
        "primary-fixed-dim": "#ffb3ac",
        "on-tertiary-fixed": "#151c27",
        "tertiary-fixed": "#dce2f3",
        "tertiary-container": "#6e7583",
        "primary-container": "#e2242a",
        "inverse-surface": "#2e3132",
        "on-background": "#191c1d",
        "on-primary": "#ffffff",
        "primary": "#bb0017",
        "on-tertiary-container": "#fefcff",
        "surface-dim": "#d9dadb",
        "surface": "#f8f9fa",
        "secondary-fixed-dim": "#c0c6db",
        "error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "24px",
        "section-padding": "120px",
        "gutter": "32px",
        "margin-mobile": "20px",
        "unit": "8px",
        "stack-sm": "12px",
        "container-max": "1280px",
        "stack-lg": "48px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "h2": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "button": ["Inter"],
        "h3": ["Inter"],
        "h4": ["Inter"],
        "body-lg": ["Inter"],
        "h1": ["Inter"]
      },
      fontSize: {
        "h2": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "button": ["16px", {"lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "h3": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "h4": ["24px", {"lineHeight": "1.4", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "h1": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800"}]
      },
      boxShadow: {
        'ambient': '0 10px 30px rgba(0, 0, 0, 0.05)',
        'ambient-hover': '0 15px 35px rgba(0, 0, 0, 0.08)',
        'red-glow': '0 10px 25px rgba(187, 0, 23, 0.15)',
      }
    },
  },
  plugins: [],
}
